a few bugfixes for instdir

diff --git a/Couenne/configure b/Couenne/configure
--- a/Couenne/configure
+++ b/Couenne/configure
@@ -21943,9 +21943,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of ThirdParty with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of ThirdParty with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/ThirdParty/README; then
+		     coin_has_thirdparty=installed
+		     THIRDPARTYINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -22007,13 +22008,30 @@ fi
 if test $coin_has_thirdparty = installed; then
   echo "$as_me:$LINENO: result: installed in $THIRDPARTYINSTDIR" >&5
 echo "${ECHO_T}installed in $THIRDPARTYINSTDIR" >&6
-  # Check for header
+  if test -r $THIRDPARTYINSTDIR/share/doc/coin/ThirdParty/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $THIRDPARTYINSTDIR/share/doc/coin/ThirdParty/README should be available if ThirdParty is installed" >&5
+echo "$as_me: error: $THIRDPARTYINSTDIR/share/doc/coin/ThirdParty/README should be available if ThirdParty is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_thirdparty" >&5
 echo "${ECHO_T}$coin_has_thirdparty" >&6
+  if test $coin_has_thirdparty != notGiven &&
+     test $coin_has_thirdparty != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of ThirdParty" >&5
+echo $ECHO_N "checking for source code location of ThirdParty... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $THIRDPARTYSRCDIR" >&5
+echo "${ECHO_T}$THIRDPARTYSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of ThirdParty" >&5
+echo $ECHO_N "checking for object code location of ThirdParty... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $THIRDPARTYOBJDIR" >&5
+echo "${ECHO_T}$THIRDPARTYOBJDIR" >&6
+  fi
 fi
 
 echo "$as_me:$LINENO: checking for COIN project CoinUtils" >&5
@@ -22109,9 +22127,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of CoinUtils with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of CoinUtils with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/CoinUtils/README; then
+		     coin_has_coinutils=installed
+		     COINUTILSINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -22173,13 +22192,30 @@ fi
 if test $coin_has_coinutils = installed; then
   echo "$as_me:$LINENO: result: installed in $COINUTILSINSTDIR" >&5
 echo "${ECHO_T}installed in $COINUTILSINSTDIR" >&6
-  # Check for header
+  if test -r $COINUTILSINSTDIR/share/doc/coin/CoinUtils/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $COINUTILSINSTDIR/share/doc/coin/CoinUtils/README should be available if CoinUtils is installed" >&5
+echo "$as_me: error: $COINUTILSINSTDIR/share/doc/coin/CoinUtils/README should be available if CoinUtils is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_coinutils" >&5
 echo "${ECHO_T}$coin_has_coinutils" >&6
+  if test $coin_has_coinutils != notGiven &&
+     test $coin_has_coinutils != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of CoinUtils" >&5
+echo $ECHO_N "checking for source code location of CoinUtils... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $COINUTILSSRCDIR" >&5
+echo "${ECHO_T}$COINUTILSSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of CoinUtils" >&5
+echo $ECHO_N "checking for object code location of CoinUtils... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $COINUTILSOBJDIR" >&5
+echo "${ECHO_T}$COINUTILSOBJDIR" >&6
+  fi
 fi
 
 echo "$as_me:$LINENO: checking for COIN project Clp" >&5
@@ -22275,9 +22311,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Clp with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of Clp with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/Clp/README; then
+		     coin_has_clp=installed
+		     CLPINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -22339,13 +22376,30 @@ fi
 if test $coin_has_clp = installed; then
   echo "$as_me:$LINENO: result: installed in $CLPINSTDIR" >&5
 echo "${ECHO_T}installed in $CLPINSTDIR" >&6
-  # Check for header
+  if test -r $CLPINSTDIR/share/doc/coin/Clp/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $CLPINSTDIR/share/doc/coin/Clp/README should be available if Clp is installed" >&5
+echo "$as_me: error: $CLPINSTDIR/share/doc/coin/Clp/README should be available if Clp is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_clp" >&5
 echo "${ECHO_T}$coin_has_clp" >&6
+  if test $coin_has_clp != notGiven &&
+     test $coin_has_clp != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of Clp" >&5
+echo $ECHO_N "checking for source code location of Clp... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $CLPSRCDIR" >&5
+echo "${ECHO_T}$CLPSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of Clp" >&5
+echo $ECHO_N "checking for object code location of Clp... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $CLPOBJDIR" >&5
+echo "${ECHO_T}$CLPOBJDIR" >&6
+  fi
 fi
 
 echo "$as_me:$LINENO: checking for COIN project Bonmin" >&5
@@ -22441,9 +22495,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Bonmin with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of Bonmin with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/Bonmin/README; then
+		     coin_has_bonmin=installed
+		     BONMININSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -22505,13 +22560,30 @@ fi
 if test $coin_has_bonmin = installed; then
   echo "$as_me:$LINENO: result: installed in $BONMININSTDIR" >&5
 echo "${ECHO_T}installed in $BONMININSTDIR" >&6
-  # Check for header
+  if test -r $BONMININSTDIR/share/doc/coin/Bonmin/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $BONMININSTDIR/share/doc/coin/Bonmin/README should be available if Bonmin is installed" >&5
+echo "$as_me: error: $BONMININSTDIR/share/doc/coin/Bonmin/README should be available if Bonmin is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_bonmin" >&5
 echo "${ECHO_T}$coin_has_bonmin" >&6
+  if test $coin_has_bonmin != notGiven &&
+     test $coin_has_bonmin != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of Bonmin" >&5
+echo $ECHO_N "checking for source code location of Bonmin... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $BONMINSRCDIR" >&5
+echo "${ECHO_T}$BONMINSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of Bonmin" >&5
+echo $ECHO_N "checking for object code location of Bonmin... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $BONMINOBJDIR" >&5
+echo "${ECHO_T}$BONMINOBJDIR" >&6
+  fi
 fi
 
 echo "$as_me:$LINENO: checking for COIN project Ipopt" >&5
@@ -22607,9 +22679,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Ipopt with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of Ipopt with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/Ipopt/README; then
+		     coin_has_ipopt=installed
+		     IPOPTINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -22671,13 +22744,30 @@ fi
 if test $coin_has_ipopt = installed; then
   echo "$as_me:$LINENO: result: installed in $IPOPTINSTDIR" >&5
 echo "${ECHO_T}installed in $IPOPTINSTDIR" >&6
-  # Check for header
+  if test -r $IPOPTINSTDIR/share/doc/coin/Ipopt/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $IPOPTINSTDIR/share/doc/coin/Ipopt/README should be available if Ipopt is installed" >&5
+echo "$as_me: error: $IPOPTINSTDIR/share/doc/coin/Ipopt/README should be available if Ipopt is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_ipopt" >&5
 echo "${ECHO_T}$coin_has_ipopt" >&6
+  if test $coin_has_ipopt != notGiven &&
+     test $coin_has_ipopt != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of Ipopt" >&5
+echo $ECHO_N "checking for source code location of Ipopt... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $IPOPTSRCDIR" >&5
+echo "${ECHO_T}$IPOPTSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of Ipopt" >&5
+echo $ECHO_N "checking for object code location of Ipopt... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $IPOPTOBJDIR" >&5
+echo "${ECHO_T}$IPOPTOBJDIR" >&6
+  fi
 fi
 
 echo "$as_me:$LINENO: checking for COIN project Cbc" >&5
@@ -22773,9 +22863,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Cbc with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of Cbc with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/Cbc/README; then
+		     coin_has_cbc=installed
+		     CBCINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -22837,13 +22928,30 @@ fi
 if test $coin_has_cbc = installed; then
   echo "$as_me:$LINENO: result: installed in $CBCINSTDIR" >&5
 echo "${ECHO_T}installed in $CBCINSTDIR" >&6
-  # Check for header
+  if test -r $CBCINSTDIR/share/doc/coin/Cbc/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $CBCINSTDIR/share/doc/coin/Cbc/README should be available if Cbc is installed" >&5
+echo "$as_me: error: $CBCINSTDIR/share/doc/coin/Cbc/README should be available if Cbc is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_cbc" >&5
 echo "${ECHO_T}$coin_has_cbc" >&6
+  if test $coin_has_cbc != notGiven &&
+     test $coin_has_cbc != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of Cbc" >&5
+echo $ECHO_N "checking for source code location of Cbc... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $CBCSRCDIR" >&5
+echo "${ECHO_T}$CBCSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of Cbc" >&5
+echo $ECHO_N "checking for object code location of Cbc... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $CBCOBJDIR" >&5
+echo "${ECHO_T}$CBCOBJDIR" >&6
+  fi
 fi
 
 echo "$as_me:$LINENO: checking for COIN project Osi" >&5
@@ -22939,9 +23047,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Osi with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of Osi with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/Osi/README; then
+		     coin_has_osi=installed
+		     OSIINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -23003,13 +23112,30 @@ fi
 if test $coin_has_osi = installed; then
   echo "$as_me:$LINENO: result: installed in $OSIINSTDIR" >&5
 echo "${ECHO_T}installed in $OSIINSTDIR" >&6
-  # Check for header
+  if test -r $OSIINSTDIR/share/doc/coin/Osi/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $OSIINSTDIR/share/doc/coin/Osi/README should be available if Osi is installed" >&5
+echo "$as_me: error: $OSIINSTDIR/share/doc/coin/Osi/README should be available if Osi is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_osi" >&5
 echo "${ECHO_T}$coin_has_osi" >&6
+  if test $coin_has_osi != notGiven &&
+     test $coin_has_osi != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of Osi" >&5
+echo $ECHO_N "checking for source code location of Osi... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $OSISRCDIR" >&5
+echo "${ECHO_T}$OSISRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of Osi" >&5
+echo $ECHO_N "checking for object code location of Osi... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $OSIOBJDIR" >&5
+echo "${ECHO_T}$OSIOBJDIR" >&6
+  fi
 fi
 
 echo "$as_me:$LINENO: checking for COIN project Cgl" >&5
@@ -23105,9 +23231,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Cgl with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of Cgl with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/Cgl/README; then
+		     coin_has_cgl=installed
+		     CGLINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -23169,13 +23296,30 @@ fi
 if test $coin_has_cgl = installed; then
   echo "$as_me:$LINENO: result: installed in $CGLINSTDIR" >&5
 echo "${ECHO_T}installed in $CGLINSTDIR" >&6
-  # Check for header
+  if test -r $CGLINSTDIR/share/doc/coin/Cgl/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $CGLINSTDIR/share/doc/coin/Cgl/README should be available if Cgl is installed" >&5
+echo "$as_me: error: $CGLINSTDIR/share/doc/coin/Cgl/README should be available if Cgl is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_cgl" >&5
 echo "${ECHO_T}$coin_has_cgl" >&6
+  if test $coin_has_cgl != notGiven &&
+     test $coin_has_cgl != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of Cgl" >&5
+echo $ECHO_N "checking for source code location of Cgl... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $CGLSRCDIR" >&5
+echo "${ECHO_T}$CGLSRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of Cgl" >&5
+echo $ECHO_N "checking for object code location of Cgl... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $CGLOBJDIR" >&5
+echo "${ECHO_T}$CGLOBJDIR" >&6
+  fi
 fi
 
 echo "$as_me:$LINENO: checking for COIN project Couenne" >&5
@@ -23271,9 +23415,10 @@ if test "${with_coin_instdir+set}" = set; then
 echo "$as_me: error: argument for --with-coin-instdir not a directory" >&2;}
    { (exit 1); exit 1; }; }
 		   fi
-		   { echo "$as_me:$LINENO: WARNING: Cannot verify availability of Couenne with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&5
-echo "$as_me: WARNING: Cannot verify availability of Couenne with --with-coin-instdir flag.  Project manager needs to provide name of header to look for" >&2;}
-
+		   if test -r $withval/share/doc/coin/Couenne/README; then
+		     coin_has_couenne=installed
+		     COUENNEINSTDIR=`cd $withval; pwd`
+		   fi
 fi;
     fi
 
@@ -23335,13 +23480,30 @@ fi
 if test $coin_has_couenne = installed; then
   echo "$as_me:$LINENO: result: installed in $COUENNEINSTDIR" >&5
 echo "${ECHO_T}installed in $COUENNEINSTDIR" >&6
-  # Check for header
+  if test -r $COUENNEINSTDIR/share/doc/coin/Couenne/README; then
 
-  # Check for library (this is not qo reliable)
+  :
+else
+  { { echo "$as_me:$LINENO: error: $COUENNEINSTDIR/share/doc/coin/Couenne/README should be available if Couenne is installed" >&5
+echo "$as_me: error: $COUENNEINSTDIR/share/doc/coin/Couenne/README should be available if Couenne is installed" >&2;}
+   { (exit 1); exit 1; }; }
+  :
+fi
 
 else
   echo "$as_me:$LINENO: result: $coin_has_couenne" >&5
 echo "${ECHO_T}$coin_has_couenne" >&6
+  if test $coin_has_couenne != notGiven &&
+     test $coin_has_couenne != skipping; then
+    echo "$as_me:$LINENO: checking for source code location of Couenne" >&5
+echo $ECHO_N "checking for source code location of Couenne... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $COUENNESRCDIR" >&5
+echo "${ECHO_T}$COUENNESRCDIR" >&6
+    echo "$as_me:$LINENO: checking for object code location of Couenne" >&5
+echo $ECHO_N "checking for object code location of Couenne... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $COUENNEOBJDIR" >&5
+echo "${ECHO_T}$COUENNEOBJDIR" >&6
+  fi
 fi
 
 
