fixed some warnings. Including SCIP for use in Feas Pump.

diff --git a/Couenne/configure b/Couenne/configure
--- a/Couenne/configure
+++ b/Couenne/configure
@@ -23362,7 +23362,9 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
-# SCIP (for use in Feasibility Pump)
+# FIXME: add symbol for SCIP (any symbol gives an error for now)
+
+# SCIP (used in Feasibility Pump)
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -23426,12 +23428,12 @@ echo "${ECHO_T}no" >&6
 # If argument 3 (file) is given, check for the file. Typically this will be a
 # header file, but that's not assumed.
 
-    if test -r $SCPINCDIR/scip.h; then
+    if test -r $SCPINCDIR/scip/scip.h; then
 
   :
 else
-  { { echo "$as_me:$LINENO: error: Cannot find file scip.h in $SCPINCDIR" >&5
-echo "$as_me: error: Cannot find file scip.h in $SCPINCDIR" >&2;}
+  { { echo "$as_me:$LINENO: error: Cannot find file scip/scip.h in $SCPINCDIR" >&5
+echo "$as_me: error: Cannot find file scip/scip.h in $SCPINCDIR" >&2;}
    { (exit 1); exit 1; }; }
   :
 fi
@@ -23444,83 +23446,6 @@ fi
 # Force the use of C as the best single choice amongst C++, C, and Fortran.
 # Obviously, this has limits.
 
-    if test x"$scip_libcheck" != xno; then
-	   coin_save_LIBS="$LIBS"
-	   LIBS="$SCPLIB "
-	   coin_SCP_link=no
-	   ac_ext=c
-ac_cpp='$CPP $CPPFLAGS'
-ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_c_compiler_gnu
-
-	   for fnm in SCIPcreate ; do
-	     echo "$as_me:$LINENO: checking whether symbol $fnm is available with SCP" >&5
-echo $ECHO_N "checking whether symbol $fnm is available with SCP... $ECHO_C" >&6
-	     cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-int
-main ()
-{
-$fnm()
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-		  coin_SCP_link=yes
-		  break
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-	   done
-	   ac_ext=c
-ac_cpp='$CPP $CPPFLAGS'
-ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
-ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_c_compiler_gnu
-
-           LIBS="$coin_save_LIBS"
-	   if test x"$coin_SCP_link" != xyes ; then
-	     { { echo "$as_me:$LINENO: error: Cannot find symbol(s) SCIPcreate with SCP" >&5
-echo "$as_me: error: Cannot find symbol(s) SCIPcreate with SCP" >&2;}
-   { (exit 1); exit 1; }; }
-	   fi
-	 fi
 
 
 # If we make it this far, we've verified the file and linked the function. Add
